### ISSUE TITLE
Applying to launcher's bug

### ISSUE THREAD

**Issue by twoone-3** [RichardLuo0/global-icon-pack-android#1]
In Settings and System ui , the module is working properly. But when I test on my Launcher, it's maybe have some problems, just like this photo

![Screenshot_20241201-091644_Paranoid_Launcher](https://github.com/user-attachments/assets/8622c2d8-390b-4cda-8f26-ddcd7ce65a29)
The circle icon is from my icon pack , and the square icons originally support Android Icon.
In normally, they should be:
![Screenshot_20241201-092412_Paranoid_Launcher](https://github.com/user-attachments/assets/2bb25cde-0bfa-4fda-b6ad-003a1179e06a)

My system is AOSPA Android 14, Launcher is Paranoid Launcher that based on aosp launcher, and I have tried turning "No Force Shape" on and off, but nothings happening.

**Comment by twoone-3** [comment]
It works, but what confuses me is that it seems that all icons are forcibly
clipped into circles. I don’t know if this is the expected behavior.

For example, the usim card application in the upper right corner was
originally a card icon without background, but now it has been cut off.

RichardLuo ***@***.***> 于 2024年12月1日周日 15:33写道：

**Comment by twoone-3** [comment]
> Try this: https://github.com/RichardLuo0/global-icon-pack-android/actions/runs/12105714620

I have tried CI v9 and v11.
"No force shape" still cut the original image 
![Screenshot_20241202-074254_Paranoid_Launcher](https://github.com/user-attachments/assets/7ea51540-89f1-46b0-8751-419f115352df)
But in settings it works well 
![Screenshot_20241202-074429_设置](https://github.com/user-attachments/assets/9adedb9f-bd86-4017-aedd-b14505e7b0f5)

**Comment by RichardLuo0** [comment]
Try the latest from actions.

**Comment by twoone-3** [comment]
Ok,it works fine 😃 thank you

**Comment by twoone-3** [comment]
[LSPosed_2024-12-03T00_36_16.749018.zip](https://github.com/user-attachments/files/17981026/LSPosed_2024-12-03T00_36_16.749018.zip)
After half day, the launcher crash once again and again 😭

**Comment by RichardLuo0** [comment]
Did you remember what you were doing at that time?

**Comment by RichardLuo0** [comment]
Also always test the latest version. I don't know which version you are on.

**Comment by twoone-3** [comment]
Sorry, I don't remember what I did, but I update CI 15 now. It works as intended, it's need to test it's stability.
If there have any questions, I will comment here🫡
