### ISSUE TITLE
[FEATURE]有没有办法能让图标包只在桌面生效而抽屉不生效？

### ISSUE THREAD

**Issue by dary1zhu** [RichardLuo0/global-icon-pack-android#11]
这样如果图标包没有自动遮罩也没有办法在别的图标包里选的话，抽屉里没有应用的图标跟其它也不会违和了，想要的支持的应用就添加到桌面。当然我可以选有自动遮罩的图标包，只是建议哈。

**Comment by RichardLuo0** [comment]
目前的实现很难做到这个。
我建议你还是自己解包然后自己添加遮罩进去 重新打包
以及你可以截图给我看一下吗？

相关链接：
https://kvaesitso.mm20.de/docs/developer-guide/integrations/icon-packs.html
https://developer.android.com/tools/aapt2?hl=zh-cn

**Comment by dary1zhu** [comment]
截图如下，不适配的就有很违和。没事大佬，难就算了，我找找不适配应用遮罩做的比较好的图标包吧，感谢。
![Screenshot_20241231-155919](https://github.com/user-attachments/assets/cd6e9270-2093-4bde-84a3-71597fc802bb)

**Comment by RichardLuo0** [comment]
像这种的遮罩也难以解决，你要不只能自己做图标了🥲
